### ISSUE TITLE
setup.py: create a proper setup script

### ISSUE THREAD

**Issue by blshkv** [derv82/wifite2#102]
please create a proper script so it would be easier to install, upgrade and uninstall the tool.
Thank you

**Comment by kimocoder** [comment]
This is also a good idea. I support this one. +1

**Comment by derv82** [comment]
Alright, added setup.py & changed some things around.

`sudo python setup.py install` will install wifite so it can be used in python (`import wifite`) and can be executed from any terminal (via just `wifite`).

I *did* remove `Wifite.py` (from the root dir) and moved it to `bin/wifite` -- hopefully this doesn't break a bunch of other people's workflows...

If it looks good, feel free to close. If there's any bugs or something is missing, let me know.

**Comment by blshkv** [comment]
Almost there, I have two comments:
 - the main binary must be installed into /usr/sbin since we expect root user to run it;
 - wordlist-top4800-probable.txt file is getting installed into "/usr" (prefix) which is wrong

**Comment by blshkv** [comment]
FYI, the second issue is tricky, we had a long discussion with an another package:
https://github.com/mschwager/fierce/issues/25#issuecomment-364584353

and end up using ```package_data```  instead of data_files. The downside of this approach is that this file is getting installed for each python dir (multiple times)

The more logical path would be something like ```/usr/share/wifite2/wordlist-top4800-probable.txt``` if possible

**Comment by derv82** [comment]
Commit message says it all.

I'm testing on ParrotSec OS btw.

For the wordlist, I specified `share/wordlists/wordlist-top4800...` and it's installing to `/usr/local/share/wordlist-top4800...` -- might be different on other distros. But that should avoid copying the file around elsewhere.

For `/usr/sbin`, I was able to change the install directory to `/usr/sbin` using `setup.cfg`'s `install-scripts` directive.

Seems to work for me using just `sudo python setup.py install`.

Once I get the :+1: I will bump minor version (2.1.10) and close the issue.

**Comment by blshkv** [comment]
Please excuse my meticulousness, I have already have few dictionaries in ```share/dict``` and that seems a standard place according FHS:
```/usr/share/dict : Word lists (optional)```

Would you consider? If not, this is fine

**Comment by blshkv** [comment]
I think you forgot to change it in the config as well:


https://github.com/derv82/wifite2/blob/b889cb93af92120d1f2074e964cd4b70d63062ce/wifite/config.py#L88

**Comment by derv82** [comment]
Config was updated and it should be good now.

**Comment by blshkv** [comment]
Awesome, thanks for your work!

**Comment by blshkv** [comment]
Hi again, I noticed that we forgot to add required and optional dependencies. You might want to create the typical ```requirements.txt```  and ```requirements_opt.txt``` as an example and call it from setup.py

**Comment by derv82** [comment]
Wifite only uses the Python standard library, so I don't think there are any required/optional *pythonic* dependencies.

I would like to have `setup.py` define *system dependencies* (like `aircrack-ng`, `ifconfig`, `reaver`, etc) but I don't think that's what `setup.py` is for.

Let me know if I'm misunderstanding your comment, e.g. if there's dependencies that should be included in `setup.py`.

**Comment by blshkv** [comment]
that is correct, I was talking about non-python packages. By right, these tools should have a python bindning package which would call its API but we dont have it. My problem that there is no official list of required tools and it's not easy to keep track the required list. For example, I noticed recently that the tool crashes if  hcxdumptool and hcxtools are not installed. I have also just realised that the dev-python/pexpect is no longer required. I'm not sure what is the best way for it.

**Comment by derv82** [comment]
> there is no official list of required tools and it's not easy to keep track the required list

README has the list with install links: https://github.com/derv82/wifite2/#required-tools

Also Wifite checks for required/optional dependencies at startup & warns if any are missing (includes links to repos).

> I noticed recently that the tool crashes if hcxdumptool and hcxtools are not installed.

This should not be the case... I just tested the latest version by editing the program names (appending `asdf` to the end of `hashcat`, `hcxdumptools`, and `hcxpcaptools`):

![image](https://user-images.githubusercontent.com/993464/44632258-48cf4b00-a92c-11e8-819c-574eb1fd9fbf.png)

![image](https://user-images.githubusercontent.com/993464/44632250-33f2b780-a92c-11e8-9dd2-386fb129c33e.png)

If you're getting crashes, [create a new Github issue](https://github.com/derv82/wifite2/issues/new) and I'll look into it.

> I'm not sure what is the best way to keep track of it.

I think built-in dependency checking is a decent way of getting this working. I thought about allowing Wifite to install the dependencies for the user (maybe just `apt-get`), but I don't know enough about linux package management to feel confident in doing that.

**Comment by blshkv** [comment]
no, no, no. Please do not go to that path and do not install tools yourself. Tools should not install or modify any system files, this is a malicious behaviour. 

The current approach is fine, here is the bug report https://github.com/derv82/wifite2/issues/131.

Thanks
