### ISSUE TITLE
Crush on Ctrl+C after networks been found

### ISSUE THREAD

**Issue by WhiteOnBlackCode** [derv82/wifite2#103]
Wifite 2.1.6

```
[+] Scanning. Found 10 target(s), 0 client(s). Ctrl+C when ready                                       
 [!] Error: Airodump has stopped

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/home/maximus/clones/wifite2/wifite/wifite.py", line 258, in run
 [!]        w.main()
 [!]    File "/home/maximus/clones/wifite2/wifite/wifite.py", line 47, in main
 [!]        self.run()
 [!]    File "/home/maximus/clones/wifite2/wifite/wifite.py", line 135, in run
 [!]        s = Scanner()
 [!]    File "/home/maximus/clones/wifite2/wifite/util/scanner.py", line 42, in __init__
 [!]        self.targets = airodump.get_targets()
 [!]    File "/home/maximus/clones/wifite2/wifite/tools/airodump.py", line 182, in get_targets
 [!]        raise Exception('Airodump has stopped')
 [!]  Exception: Airodump has stopped

 [!] Exiting
```

**Comment by GGGunrunner** [comment]
Yeah, same thing - after I'm getting a list of networks, I press Ctrl-C and in maybe 3/4 of cases it crashes....

In 1/4 of cases I can continue and select the network. No big deal, but still quite annoying.... I suppose the way we intercept the keyboard can be improved.

===
[!] Airodump exited unexpectedly (Code: 0) Command: airodump-ng wlan1mon -a -w /tmp/wifite9Xl2nK/airodump --write-interval 1 --output-format pcap,csv                                                                                       

 [!] Error: No targets found. You may need to wait longer, or you may have issues with your wifi card

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/root/wifite2/wifite/wifite.py", line 258, in run
 [!]        w.main()
 [!]    File "/root/wifite2/wifite/wifite.py", line 47, in main
 [!]        self.run()
 [!]    File "/root/wifite2/wifite/wifite.py", line 140, in run
 [!]        targets = s.select_targets()
 [!]    File "/root/wifite2/wifite/util/scanner.py", line 179, in select_targets
 [!]        + " or you may have issues with your wifi card")
 [!]  Exception: No targets found. You may need to wait longer, or you may have issues with your wifi card

 [!] Exiting

**Comment by rrsit** [comment]
same here.

**Comment by kocheko** [comment]
Same issue. Still no fix?

**Comment by WhiteOnBlackCode** [comment]
This issue and #114 are the same!

**Comment by derv82** [comment]
I was able to reproduce the crash by pressing `ctrl+c` right when the list of targets is getting updated.

Pretty sure I fixed this in the latest version (`2.1.7`), pushed just now. Let me know if you still hit this bug.

**Comment by WhiteOnBlackCode** [comment]
Cannot reproduce it anymore, very well!

**Comment by kocheko** [comment]
[+] Scanning. Found 13 target(s), 1 client(s). Ctrl+C when ready               
 [!] Error: Airodump has stopped

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/share/wifite/wifite/wifite.py", line 258, in run
 [!]        w.main()
 [!]    File "/usr/share/wifite/wifite/wifite.py", line 47, in main
 [!]        self.run()
 [!]    File "/usr/share/wifite/wifite/wifite.py", line 135, in run
 [!]        s = Scanner()
 [!]    File "/usr/share/wifite/wifite/util/scanner.py", line 42, in __init__
 [!]        self.targets = airodump.get_targets()
 [!]    File "/usr/share/wifite/wifite/tools/airodump.py", line 182, in get_targets
 [!]        raise Exception('Airodump has stopped')
 [!]  Exception: Airodump has stopped


so still no fix, should i...what? reinstall wifite? how?

this is what i put in

git clone https://github.com/derv82/wifite.git

**Comment by mamilux** [comment]
Hi Derv82 i have same issue with Nexus5 wifite 2.2.5. Can you help me to? Wlan1 working but wlan0 not. Airodump working without any problem with wlan0. Thanks in advance.

**Comment by thechaku** [comment]
have you guys upgraded your linux to newer version?

**Comment by tracid1987** [comment]
Hello. Today i had live booted Kali Linux from USB for the first time. I have update/upgraded it, then after running wifite it required only Pyrit to install. so i have installed Pyrit. After this when running wifite (in root terminal) it has only Network Manager conflict. I have tried both with running and killing Network Manager and running wifite and it says my WIFI module is in monitor mode, it finds my network and offers CTRL+C to finish scanning. After i push the combination it terminates wifite without any other messages most of the time. Sometimes it leaves the "select network" line there but i see it only after exiting wifite so i cannot make any decisions.  BTW I dont have any USB WIFI module yet, I am using my laptops inbuilt Atheros AR9285 in live boot (so not Virtual Machine).  what could be the problem?

**Comment by codeswhite** [comment]
@tracid1987 The issue could be that you are not capturing any traffic with your WiFi card..
Please try **manually** running `airmon-ng` and `airodump-ng` to find out either its a problem with Wifite or with your environment.

**Comment by tracid1987** [comment]
I have just succesfully cracked my own WIFI password using airmon,airodump,aircrack without any problems for the first attempt. So my WIFI modul is okay.
Something is going on with wifite. When i push CTRL+C it exits the script and leaves behind the target selection and cracking result lines (without allowing me to choose anything so it jist writes the lines out and exits).

Another strange thing i have observed,i dont know if i have to mention it here.maybe related if something is wrong with the terminal maybe. I am new to this stuff and i wanted to enable/disable monitor mode and was searching for commands how to do it.i found
sudo ifconfig wlan0 down
sudo iwconfig wlan0 mode managed
sudo ifconfig wlan0 up

If i perform these 3 commands the mode does not change but it malfunctions the system- the network and internet connection gets disconnected and if i try to run network related scripts (i believe it is not script specific- every script i have tried malfunctioned) sometimes it writes a few lines of desired result,sometimes not and it just displays the white rectange (cursor) like it is working on something but i can still type letters but it is not the command line. I cannot exit the non-responding srcipt by CTRL+C,i can only exit the whole terminal. Then i have to restart Kali and then it is working again.

I dont know if it has some correlation with the original problem with wifite.but wifite isnt working good neither after a clean restart. By executing airmon-ng start wlan0 prior to wifite does not make any difference. Conflicting services are killed. And still no difference... I tried to clone wifite2 from github and running it, same result.
