### ISSUE TITLE
After executing ./wifite.py ERROR 

### ISSUE THREAD

**Issue by codeCesar** [derv82/wifite2#107]
[!] Error: module 'os' has no attribute 'getuid'

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "C:\Users\adios\Desktop\wifite2\wifite\wifite.py", line 258, in run
 [!]        w.main()
 [!]    File "C:\Users\adios\Desktop\wifite2\wifite\wifite.py", line 29, in main
 [!]        if os.getuid() != 0:
 [!]    AttributeError: module 'os' has no attribute 'getuid'

 [!] Exiting
 
windows 10 pro using Git Bash

**Comment by WhiteOnBlackCode** [comment]
there is no support for windows 10, although it might work if you run it in "bash on windows" feature
https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by codeCesar** [comment]
Thanks ill try that

**Comment by kimocoder** [comment]
@codeCesar this may be closed. It does not support Windows 10.
