### ISSUE TITLE
Capture all traffic from selected ESSID

### ISSUE THREAD

**Issue by crecos** [derv82/wifite2#109]
I know that this software is primarily designed to breaking wifi. But it's so simple to use that he misses this feature. You can add the option to save all traffic from wireless network similar to handshakes?

**Comment by examin** [comment]
Do you mean a Man in middle type attack?

**Comment by derv82** [comment]
There's other tools for capturing and analyzing traffic, check out [bettercap](https://www.bettercap.org/), but there's probably others that are easy to use, listen for passwords, URLs, images, etc.

Wifite *could* connect to a network & sniff traffic, but... that would be better suited for it's own tool, and there's nothing common between what Wifite does now and what you have proposed.

Right now, Wifite does not *connect* to any networks; it is purely for retrieving the passwords of protected networks.
