### ISSUE TITLE
Wifite2 fails with disk full

### ISSUE THREAD

**Issue by RobertLHarris** [derv82/wifite2#110]
I kept getting disk full issues when running longer scans on my Pineapple.  I had to patch it to use /sd/tmp instead of /tmp.  Maybe a command line for "--alt-tmp" or something or an env variable.

Also, it wasn't creating /tmp/<temp_file> and I had to add:

  if not os.path.exists(tmp):
    os.makedirs(tmp)

I would branch and submit but haven't gotten that good with Git yet.

**Comment by kimocoder** [comment]
Adding a switch for choosing directory for cache / saving would be a good idea not only for your Pineapple but also NetHunter devices and possible RPI's in some cases. Great suggestion!

**Comment by derv82** [comment]
I guess an option like `--temp-dir /path/to/temp` would alleviate this problem.

And I'm using Python's built-in [`tempfile`](https://docs.python.org/2/library/tempfile.html) library, so if that's failing to create the root `/tmp` directory, then... yikes.

**Comment by derv82** [comment]
**Update/Fix**: You can change the temp directory using environment variables in the command-line ([stackoverflow](https://stackoverflow.com/questions/18280245/where-does-python-tempfile-writes-its-files#18280309)).

If you usually run wifite using `wifite`, then do something like this:

```bash
TMPDIR=/path/to/the/tmp wifite
```

Or if you run wifite using `python -m wifite` then:

```bash
TMPDIR=/path/to/the/tmp python -m wifite
```

This will make wifite write temp files to `/path/to/the/tmp/wifiteXXXXX`. where XXXX is some randomly-generated letters.

**Note**: You have to make sure the path **already exists** (in the example, `/path/to/the/tmp` has to be a directory that exists).
