### ISSUE TITLE
pixie-dust fails to obtain pin that is successfully obtained via reaver or bully

### ISSUE THREAD

**Issue by vzhyvotkov** [derv82/wifite2#113]
My router's wps pin can be successfully obtained via reaver or bully but somehow wifite2 fails to do the same

Maybe i'm running it with wrong params, not sure though

`./Wifite.py --wps-only --wps` on my network

Mynet (68db) WPS Pixie-Dust: [--1s]: Failed: Timeout after 300 seconds

**Comment by examin** [comment]
reaver ,bully, and wifite all use nearly same but different methods to recover WPS pin. Wifite in your case is trying to find exact pin using pixie dust method.  Try running wifite without pixi-dust method .

**Comment by vzhyvotkov** [comment]
same, `./Wifite.py` with no params

**Comment by derv82** [comment]
You can run wifite with `-v` verbose mode to show what commands are being executed (e.g. `bully` or `reaver` with all the parameters).

Then you can try running those commands yourself (not using Wifite) and see if it still does not work.

If it still does not work, it's not a problem with Wifite; head over to the Kali forums for troubleshooting Reaver/Bully issues.
