### ISSUE TITLE
[!] Exception: Airodump has stopped.

### ISSUE THREAD

**Issue by trollmad3** [derv82/wifite2#114]
Whenever I use ``wifite --wep --require-fakeauth`` and select the first target it says
this:  
![41875565-78c578e0-7888-11e8-939d-b1fc1f2f9d84](https://user-images.githubusercontent.com/7843719/43994138-1ec42390-9d55-11e8-8f61-8a001d663af0.png)

**Comment by rrsit** [comment]
happens to me too, when hitting CTRL+C
sometimes it doesn't crash, most of the time it does. 
i use wifite without any command line parameters.

**Comment by trollmad3** [comment]
@rrsit The error happens only when there is 1 network in the area. I tried to target only `WEP` networks and there was one only. I clicked CTRL+C and it crashed.

**Comment by WhiteOnBlackCode** [comment]
seems to be resolved with: https://github.com/derv82/wifite2/pull/115

**Comment by kocheko** [comment]
Sorry but what is exactly the fix?

**Comment by WhiteOnBlackCode** [comment]
@kocheko This issue seems to be resolved with #115 , yet @derv82 have to verify the fix.

**Comment by trollmad3** [comment]
@WhiteOnBlackCode @derv82 seems to be not active on github. Last time he **ever** did something was [Aug 4, 2018.](https://i.imgur.com/K2YflYI.png)

**Comment by kimocoder** [comment]
He's checking in now and then :) hopefully soon, to merge some fixes

**Comment by trollmad3** [comment]
@kimocoder Good.

**Comment by WhiteOnBlackCode** [comment]
@kimocoder  Glad to hear!! 
@derv82  we need you :)

**Comment by derv82** [comment]
Should be fixed in `2.1.7` -- See my comment in another issue for details https://github.com/derv82/wifite2/issues/103#issuecomment-413475542

**Comment by trollmad3** [comment]
@derv82 If this bug is fixed, then I will close this issue.
