### ISSUE TITLE
Output of --crack clobbers previously exported files

### ISSUE THREAD

**Issue by mzpqnxow** [derv82/wifite2#116]
When using Wifite.py --crack, the output suggested to the user always results in the file for John to be named 'hccap.john'. For users that are using this as a copy/paste, this can be inconvenient as it will overwrite previous converted john compatible files. It would be nice if the .john file was named similarly to how the initial capture file is named: handshake_<ssid>_<hwmac>.cap rather than simply  'hccap.john'

**Comment by mzpqnxow** [comment]
Submitted a pull-request to enhance this behavior in #117 

I tested it, it can be considered a cosmetic change, but if you'd like to review it, please do. Thanks, I appreciate the work that has gone into this tool.

**Comment by mzpqnxow** [comment]
@derv let me know if you would like to accept this PR, if not I will close it. Thanks!

**Comment by derv82** [comment]
Thanks for the report & PR. I applied the changes myself to avoid merge conflicts in the PR, and closed the PR.
