### ISSUE TITLE
Feature Request - Crack existing handshakes

### ISSUE THREAD

**Issue by RChadwick7** [derv82/wifite2#119]
It would be great to have a command line option to crack all saved handshakes with common.txt (Or Rockyou or whatever)

**Comment by evrial** [comment]
+1

**Comment by derv82** [comment]
Just in case you were unaware: There *is* a `--crack` option which provides the commands to crack a *single* access point.

However, you're asking for a new feature which will automatically try to crack **all saved handshakes** (in the `./hs/` dir) using the same dictionary. Something like:

```bash
sudo ./Wifite.py --crack-all --dict /usr/share/wordlists/rockyou.txt
```

I think this feature would be useful.

Do you want to be able to choose how you crack it? E.g. `aircrack-ng`, `john`, `cowpatty`, `hashcat`, `pyrit`, etc...?

**Comment by kimocoder** [comment]
Actually, both of them would be usefull. The --crack-all to make a more automatic tool and selection of method to give is more options.

**Comment by derv82** [comment]
I updated the `--crack` option in `2.1.9` ([release notes](https://github.com/derv82/wifite2/releases/tag/2.1.9)).

Changes:

* Cracks handshakes by-default; no longer prints the commands.
* Handshake selection is similar to target selection (can be ranges `1-3` or comma-delimited (`1,3,5`)
* Supports PMKID "handshakes" (PMKID Hashes stored in `*.16800` files in the `hs` directory).

I plan on bringing back & adding features in the future:
* Accept `all` as input in handshake selection to crack all handshakes.
* Bring back the *print* option insted of auto-cracking.
* Allow users to choose cracking tool (hashcat/aircrack/cowpatty/pyrit/john)
   * Detect cracking progress (percentages, already done for aircrack but not hashcat)
   * Provide an ETA current handshake, and total ETA for all handshakes.

**Comment by derv82** [comment]
Alright version `2.2.2` has some improvements to `--crack`:
* Users can type `all` to select all handshakes.
* Users can choose `hashcat`, `aircrack`, `john`, or `cowpatty`

Commands *are* printed as they're run, but there is no way to show these commands without Wifite executing them. I don't how much of a priority this is...

And detecting cracking progress & ETA is a *hard* problem. Probably won't ever get around to doing that.

Test it out, if you're happy, feel free to resolve. Or let me know any bugs you encounter.

**Comment by evrial** [comment]
What I think is a better idea: wifite commonly used on portable devices or VM with slow CPU so there is little reason to crack if the process takes longer than 5 min, so I suggest to add the command to manually input and save the cracked password from hashcat using GPU acceleration and mark those networks to skip SSID in the future.

**Comment by kimocoder** [comment]
@RChadwick7 this issue has been resolved and the feature is implemented. please close your issue report, thanks :1st_place_medal:
