### ISSUE TITLE
WEP attack does not output the correct key

### ISSUE THREAD

**Issue by ragefan** [derv82/wifite2#125]
Hello,
I tried to crack a WEP network using wifite2 but the cracked.txt seems wrong.
The ascii_key seems invalid.
The hex_key does not seem good either.
I tried twice with same result.

The output is the following : 

```
root@Raspkali:~/tools/wifite2# cat cracked.txt
[
  {
    "bssid": "01:1E:2A:0D:BE:92",
    "hex_key": "3F:87:D4:F3:37",
    "ascii_key": null,
    "essid": "MYTESTNET",
    "date": 1534442180,
    "type": "WEP"
  },
  {
    "bssid": "01:1E:2A:0D:BE:92",
    "hex_key": "3F:87:D4:F3:37",
    "ascii_key": null,
    "essid": "MYTESTNET",
    "date": 1534447425,
    "type": "WEP"
  }
```

Thx

**Comment by derv82** [comment]
Not all WEP passwords are plaintext ascii...

That key in ascii is `?Ôó7` which is probably not what you want to enter.

Try connecting to the network using the key *without colons (`:`)* `3F87D4F337`

**Comment by ragefan** [comment]
So newbie 🥇 - Thanks !
