### ISSUE TITLE
Why does the installation of this program hcxdumptool. I wrote an error.

### ISSUE THREAD

**Issue by Kasperait** [derv82/wifite2#140]
Here is a video : https://youtu.be/LlrXzwEwNiQ

**Comment by WhiteOnBlackCode** [comment]
Hmm seems like you don't really know what you are doing.. No offence, we all had to start somewhere.

Make sure you read the documentation of the missing tool (hcxtools) which is located here: https://github.com/ZerBea/hcxtools
There are instructions which will compile and install the missing tool on your system.

When it comes to computer errors - please, ask google before asking people.

**Comment by usaflees** [comment]
When this error pops up it will actually guide you to the instructions on how to install these tools.  If you are using Kali Linux you will also need some dev packages and\or updates such as curl-dev etc. using the apt-get install function.
