### ISSUE TITLE
--band options for 5Ghz testing

### ISSUE THREAD

**Issue by cclements** [derv82/wifite2#16]
Thanks for a great time saving tool.  Could you please add configuration options for airodump to specify the "--band=a" argument?  This enables 5Ghz testing on supported cards (by default airodump only scans through 2.4Ghz)

**Comment by derv82** [comment]
There is a `-5` or `--5ghz` option, but it uses `--band=abg` which scans 2ghz and 5ghz bands. And it's *really* slow for me...

Changing `-5` to scan **only** 5ghz networks seems like a better solution.

Note: I can't seem to send `deauth` packets using `aireplay-ng` on 5ghz channels. Not sure if it's a bug in `aireplay-ng` or my wireless chipset.

**Comment by derv82** [comment]
Made the above changes (`-5` only scans 5ghz networks), commit is https://github.com/derv82/wifite2/commit/250e89b21ef319bf00751d275b2d3068df656400

Let me know if this works for you.

**Comment by wifiuk** [comment]
i am able to scan using -5 and it does scan for only 5ghz networks only using the the AWUS036ACH
