### ISSUE TITLE
Crash of wifite2 - target did not appear

### ISSUE THREAD

**Issue by wifiuk** [derv82/wifite2#18]
I had a list of 50 targets , it was going fine up until target 15

` [+] (15/49) starting attacks against XX:XX:XX:XX:XX:XX: (XXXXXX)
 [+] XXXXXXXXXX (XX:XX:XX:XX:XX:XX @ 27db) WPA Handshake capture: Waiting for target to appear...                                      
 [!] Error: Target did not appear after 20 seconds, stopping

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "./Wifite.py", line 174, in <module>
 [!]        w.main()
 [!]    File "./Wifite.py", line 38, in main
 [!]        self.run()
 [!]    File "./Wifite.py", line 123, in run
 [!]        attack.run()
 [!]    File "/root/apps/wifite2/py/AttackWPA.py", line 41, in run
 [!]        airodump_target = self.wait_for_target(airodump)
 [!]    File "/root/apps/wifite2/py/Attack.py", line 30, in wait_for_target
 [!]        % Attack.target_wait)
 [!]  Exception: Target did not appear after 20 seconds, stopping

 [!] Exiting

`
then it just crashes and dies.

**Comment by wifiuk** [comment]
ideally this should just skip that target and move on to the next one

**Comment by derv82** [comment]
(Glad I left stack traces on!)

Commit says the change "*should* resolve" this. Reopening in case it's not resolved & happens again

**Comment by wifiuk** [comment]
looks resolved

`[+] (1/28) starting attacks against XX:XX:XX:XX:XX:XX ((XX:XX:XX:XX:XX:X:))
 [+] unknown (XX:XX:XX:XX:XX:XX @ 99db) WPA Handshake capture: Waiting for target to appear...                                     
 [!] Error: Target did not appear after 20 seconds, stopping

 [+] (2/28) starting attacks against XX:XX:XX:XX:XX:XX ((XX:XX:XX:XX:XX:X:))
 [+] unknown (XX:XX:XX:XX:XX:XX @ 99db) WPA Handshake capture: Waiting for handshake...  sending deauth to XX:XX:XX:XX:XX:XX   `

**Comment by wifiuk** [comment]
looks resolved

`[+] (1/28) starting attacks against XX:XX:XX:XX:XX:XX ((XX:XX:XX:XX:XX:X:))
 [+] unknown (XX:XX:XX:XX:XX:XX @ 99db) WPA Handshake capture: Waiting for target to appear...                                     
 [!] Error: Target did not appear after 20 seconds, stopping

 [+] (2/28) starting attacks against XX:XX:XX:XX:XX:XX ((XX:XX:XX:XX:XX:X:))
 [+] unknown (XX:XX:XX:XX:XX:XX @ 99db) WPA Handshake capture: Waiting for handshake...  sending deauth to XX:XX:XX:XX:XX:XX   `

**Comment by derv82** [comment]
Sweet thanks for confirming.

**Comment by jhoutromundo** [comment]
Just to be sure, the traceback still shows up? 

I'm getting

 [!]    Traceback (most recent call last):
 [!]    File "./Wifite.py", line 138, in run
 [!]        attack.run()
 [!]    File "/root/wifite2/py/AttackWPA.py", line 45, in run
 [!]        airodump_target = self.wait_for_target(airodump)
 [!]    File "/root/wifite2/py/Attack.py", line 30, in wait_for_target
 [!]        % Attack.target_wait)
 [!]  Exception: Target did not appear after 20 seconds, stopping
