### ISSUE TITLE
wifite issue

### ISSUE THREAD

**Issue by BRRY876** [derv82/wifite2#191]
im getting this error 

[!] Killing 4 conflicting processes
 [!] stopping avahi-daemon (service avahi-daemon stop)
 [!] stopping avahi-daemon (service avahi-daemon stop)
 [!] Terminating conflicting process wpa_supplicant (PID 6004)
 [!] stopping network-manager (service network-manager stop)

 [+] Using wlan0mon already in monitor mode                                                                                                                                                   

 [+] Scanning. Found 0 target(s), 0 client(s). Ctrl+C when ready ^C                                                                                                                           
 [!] Error: No targets found. You may need to wait longer, or you may have issues with your wifi card

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/lib/python2.7/dist-packages/wifite/__main__.py", line 93, in entry_point
 [!]        wifite.start()
 [!]    File "/usr/lib/python2.7/dist-packages/wifite/__main__.py", line 54, in start
 [!]        self.scan_and_attack()
 [!]    File "/usr/lib/python2.7/dist-packages/wifite/__main__.py", line 79, in scan_and_attack
 [!]        targets = s.select_targets()
 [!]    File "/usr/lib/python2.7/dist-packages/wifite/util/scanner.py", line 189, in select_targets
 [!]        + ' or you may have issues with your wifi card')
 [!]  Exception: No targets found. You may need to wait longer, or you may have issues with your wifi card

wificard:
PHY	Interface	Driver		Chipset

phy0	wlan0		ath10k_pci	Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter (rev 31)

**Comment by BRRY876** [comment]
anyone can assist me ????????????????????

**Comment by Czechball** [comment]
This could be caused by the fact, that your internal Wifi modem doesn't properly support monitor mode. Or you didn't wait long enough for networks to appear in scans. I would recommend buying some cheap SUPPORTED wifi usb dongle and try it again.

**Comment by BRRY876** [comment]
i had the program running for 5 mins.....so i suspect its a hardware issue....gonna close the thread
