### ISSUE TITLE
aircrack-ng has added PMKID attack vectors

### ISSUE THREAD

**Issue by kimocoder** [derv82/wifite2#198]
aircrack-ng has added PMKID attack support, that allows is to:

1. Trade the 2 dependencies and use aircrack-ng method
2. Add an option on which method to use.

aircrack-ng commit:
https://github.com/aircrack-ng/aircrack-ng/commit/50c8957344b1a418eef3dd959ca087933497c56a

**Comment by RaduNico** [comment]
A secondary note is that we need to update the dockerfile to use a more recent version of aircrack - currently we use aircrack-ng 1.2.
