### ISSUE TITLE
how about i just dont wants to use WPS PIN?........

### ISSUE THREAD

**Issue by 687766616e** [derv82/wifite2#215]
`--no-wps               Never use WPS PIN & Pixie-Dustattacks on targets`
`--no-pixie             Never use WPS Pixie-Dust attack (use PIN attack)`
how about i just dont wants to use WPS PIN?

**Comment by LowSkillDeveloper** [comment]
`--pixie                Only use WPS Pixie-Dust attack (do not use PIN attack)`

**Comment by RaduNico** [comment]
The answer solves your question, could you please close this?
