### ISSUE TITLE
empty handshake

### ISSUE THREAD

**Issue by ghost** [derv82/wifite2#220]

**Comment by Adonisael** [comment]
Hello . After i cracked the handshake what can i do with that ????

**Comment by mohabduls** [comment]
Whatn the name of the applications do you use ?

**Comment by SivertPL** [comment]
Which ones

Wysłano z aplikacji ProtonMail

-------- Oryginalna wiadomość --------
W dniu 14 sty 2020, 22:27, mohabduls napisał(a):

**Comment by mohabduls** [comment]
Termux or something ? 
Are wifite2 need root permission?

**Comment by SivertPL** [comment]
yes.

What country are you from?

Wysłano z aplikacji ProtonMail

-------- Oryginalna wiadomość --------
W dniu 14 sty 2020, 22:31, mohabduls napisał(a):

**Comment by mohabduls** [comment]
Im from indonesia, how about you?

**Comment by SivertPL** [comment]
Poland, hit me up on Threema and we'll talk about the thing

Y43d3ky6

Wysłano z aplikacji ProtonMail

-------- Oryginalna wiadomość --------
W dniu 14 sty 2020, 22:34, mohabduls napisał(a):

**Comment by mohabduls** [comment]
Ok

**Comment by mohabduls** [comment]
i dont have a threema, i just have whatsapp

**Comment by mohabduls** [comment]
i dont have a threema, i just have whatsapp

**Comment by kimocoder** [comment]
which version of wifite are you using?

**Comment by SivertPL** [comment]
can you get it?

Wysłano z aplikacji ProtonMail

-------- Oryginalna wiadomość --------
W dniu 14 sty 2020, 22:46, mohabduls napisał(a):

**Comment by mohabduls** [comment]
i can't, i dont have any money for download this app.
