### ISSUE TITLE
Terminal crashes when pressing ctrl c

### ISSUE THREAD

**Issue by root3d1** [derv82/wifite2#227]
I am on nethunter and when i press ctrl c to stop the scan it crashes my nethunter terminal. What can i do i cant seem to find a workaround.

**Comment by kimocoder** [comment]
Try using JuiceSSH instead. You need to activate SSH with (service SSH start) to be able to connect.

**Comment by root3d1** [comment]
> Try using JuiceSSH instead. You need to activate SSH with (service SSH start) to be able to connect.

Could you please give a brief explanation as to what you mean and how to do it sorry im not the most advanced user! Thanks!

**Comment by root3d1** [comment]
Never mind dude i worked it out and it worked thanks so much!!!
