### ISSUE TITLE
Error: Target did not appear after 60 seconds, stopping

### ISSUE THREAD

**Issue by michelep** [derv82/wifite2#229]
When a target goes too far to be attacked, that's happens:

[!] Error: Target did not appear after 60 seconds, stopping

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/wifite2/wifite/attack/all.py", line 86, in attack_single
 [!]        result = attack.run()
 [!]    File "/wifite2/wifite/attack/wpa.py", line 42, in run
 [!]        handshake = self.capture_handshake()
 [!]    File "/wifite2/wifite/attack/wpa.py", line 94, in capture_handshake
 [!]        airodump_target = self.wait_for_target(airodump)
 [!]    File "/wifite2/wifite/model/attack.py", line 24, in wait_for_target
 [!]        raise Exception('Target did not appear after %d seconds, stopping' % Attack.target_wait)
 [!]  Exception: Target did not appear after 60 seconds, stopping
 [+] Finished attacking 1 target(s), exiting
 [!] Note: Leaving interface in Monitor Mode!
 [!] To disable Monitor Mode when finished: airmon-ng stop wlan0mon

**Comment by RaduNico** [comment]
Hello! This a duplicate for the issue create by derv82 here #132. You could close this to claer a bit of the clutter.
