### ISSUE TITLE
hcx tools  

### ISSUE THREAD

**Issue by leonal0** [derv82/wifite2#236]
root@kali:~# git clone https://github.com/ZerBea/hcxtools.git
fatal: destination path 'hcxtools' already exists and is not an empty directory.
root@kali:~# cd hcxtools/
root@kali:~/hcxtools# ls
changelog      hcxhashcattool.c  usefulscripts     wlanhcx2ssid.c
com_aes.c      hcxpcaptool.c     whoismac.c        wlanhcxcat.c
com_formats.c  hcxpsktool.c      wlancap2wpasec.c  wlanhcxinfo.c
com_md5_64.c   hcxwltool.c       wlancow2hcxpmk.c  wlanhcxmnc.c
com_md5_64.h   include           wlanhashhcx.c     wlanjohn2hcx.c
common.c       license.txt       wlanhc2hcx.c      wlanpmk2hcx.c
common.h       Makefile          wlanhcx2cap.c     wlanwkp2hcx.c
com_wpa.c      manpages          wlanhcx2essid.c
hcxhash2cap.c  README.md         wlanhcx2john.c
root@kali:~/hcxtools# make
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
hcxpcaptool.c:16:10: fatal error: openssl/sha.h: No such file or directory
 #include <openssl/sha.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:79: hcxpcaptool] Error 1
root@kali:~/hcxtools#

**Comment by kimocoder** [comment]
apt-get install libssl-dev
