### ISSUE TITLE
Wifite2 cannot find any target or client

### ISSUE THREAD

**Issue by developomp** [derv82/wifite2#239]
So I have installed all the dependencies, ran the install script, and typed `sudo wifite` but it just printed the following message and didn't start anything. I am fully aware that this is not a fault of the program, but my lack of knowledge. But still, I posted this here just so I might get some help.

Here is the message I got:
```
(base) pomp@pomp:~$ sudo wifite
   .               .    
 .´  ·  .     .  ·  `.  wifite 2.2.5
 :  :  :  (¯)  :  :  :  automated wireless auditor
 `.  ·  ` /¯\ ´  ·  .´  https://github.com/derv82/wifite2
   `     /¯¯¯\     ´    


 [+] Using wlp5s0mon already in monitor mode

 [+] Scanning. Found 0 target(s), 0 client(s). Ctrl+C when ready  
```

**Comment by jjhu** [comment]
What's your wifi card or chipset?

**Comment by developomp** [comment]
I's an unsupported card my bad
