### ISSUE TITLE
[5Ghz] Deauth doesn't seem to work

### ISSUE THREAD

**Issue by derv82** [derv82/wifite2#24]
`aircrack-ng` is able to *capture* handshakes on 5ghz networks, but `aireplay-ng` can't deauth stations.

Might be my wireless card(s). Might be a bug in `aireplay-ng`. Might be how Wifite invokes `aireplay-ng`. Might be due to how 5ghz protocols are implemented.

**Comment by derv82** [comment]
Last resort: We *could* use `scapy` to send the deauthentication packets ourselves (natively in Python).

**Comment by vom513** [comment]
I tested 5ghz today with the latest git - it seemed to work.  Vanilla WPA handshake attacks, deauths sent (after the new timer logic).  FYI - I'm using an Alfa AWUS036ACH in latest Kali.

**Comment by derv82** [comment]
Found the reason it did not work for me.

Looks like `airodump-ng` sees my AP on channel `-1` instead of `149`.

This made `aireplay-ng --deauth 1` loop infinitely listening on channel `-1`.

Overriding AP detection in `aireplay-ng` (via `-D`) got it working for me.
