### ISSUE TITLE
wifite

### ISSUE THREAD

**Issue by Coder9956** [derv82/wifite2#283]
when i run wifite it shows pyrit hcxdumtool, hcxtools missing 
when i try to get these then new issuse comes with the hcxdumtool wheni press the command 
**make**  and **make install** it shows 
root@kali:~/Desktop/hcxdumptool# make
cc -O3 -Wall -Wextra -std=gnu99  -o hcxpioff hcxpioff.c  -DVERSION_TAG=\"6.0.6-4-gb617d38\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -o hcxdumptool hcxdumptool.c  -lcrypto -lssl -DVERSION_TAG=\"6.0.6-4-gb617d38\" -DVERSION_YEAR=\"2020\"
hcxdumptool.c:50:10: fatal error: openssl/evp.h: No such file or directory
 #include <openssl/evp.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:32: build] Error 1
root@kali:~/Desktop/hcxdumptool# make install
cc -O3 -Wall -Wextra -std=gnu99  -o hcxpioff hcxpioff.c  -DVERSION_TAG=\"6.0.6-4-gb617d38\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -o hcxdumptool hcxdumptool.c  -lcrypto -lssl -DVERSION_TAG=\"6.0.6-4-gb617d38\" -DVERSION_YEAR=\"2020\"
hcxdumptool.c:50:10: fatal error: openssl/evp.h: No such file or directory
 #include <openssl/evp.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:32: build] Error 1

pls help if anyone knows its remedy

**Comment by kimocoder** [comment]
So why not use "apt-get install hcxdumptool" when your not able to git clone hcx and install 'libssl-dev' ?
