### ISSUE TITLE
Unable to launch wifite2

### ISSUE THREAD

**Issue by Amal-Vincent** [derv82/wifite2#29]
I am receiving the following errors while trying to run wifite and the runtests.sh, I am running on ubuntu 16.04. The older version of wifite was running fine except for the fact that I am unable to capture handshakes on wpa2 authentication
![59e66414-4988-11e7-90fa-c4747765cc7a](https://cloud.githubusercontent.com/assets/11134381/26780042/7d2465ac-4a05-11e7-981a-0897d877f51f.png)

**Comment by Amal-Vincent** [comment]
![53f7defc-4988-11e7-92a8-aedc7e5ee4f1](https://cloud.githubusercontent.com/assets/11134381/26780062/97b66884-4a05-11e7-91b0-39ef9d5747ae.png)

**Comment by derv82** [comment]
Looks like you're using Ubuntu, or some OS distribution that *is not Kali*. From the Project page:

> Wifite2 is designed entirely for the latest version of Kali Rolling release (tested on Kali 2016.2, updated May 2017).

> This means only the latest versions of these programs are supported: Aircrack-ng suite, wash, reaver, tshark, cowpatty.

> Other pen-testing distributions (such as BackBox) have outdated versions of these suites; these distributions are not supported.

---------------

I'll leave this open as a low-priority task to update Wifite to detect when vital programs are missing or outdated. E.g. we don't need cowpatty to run Wifite.

**Comment by Amal-Vincent** [comment]
Hey @derv82 , I figured it out on my own, it is because of outdated airodump-ng , the write interval setting was introduced much later.

Thanks anyways.

Could you add the latest link to all requirement packages.

Also can I help with the development? 

:)

**Comment by Amal-Vincent** [comment]
Btw I have latest version of cowpatty installed do not know why that fails

**Comment by alfabuster** [comment]
So what about Ubuntu? Is wifite2 support ubuntu os?
