### ISSUE TITLE
hcxpacptool is missing in wifite2, hcxtools have renamed it as hcxpcapngtool in their repository, so please update the module for hcxpcaptool and rename it as hcxpacpngtool.

### ISSUE THREAD

**Issue by Joey0538** [derv82/wifite2#298]

**Comment by terminalnub** [comment]
hi, can you please tell me how to do that?

**Comment by Joey0538** [comment]
My friend, I myself dont how to do that. That's why I have posted the issue here. Also, FYI, I tried Kali Linux 2020.3 too, the problem of hcxpcaptool missing is even there. Didn't expect that to happen, Wifite is not stable on Kali and Ubuntu because of this HCXPCAPTOOL missing, what I know is that tool has been renamed as HCXPCAPNGTOOL by the developers of HCXTOOLS, but the WIFITE developers have to redirect and modify the name of the library to HCXPCAPNGTOOL instead of HCXPCAPTOOL.

**Comment by terminalnub** [comment]
Sorry, given the detailed description of the question, and the difficulty in finding an answer online, I thought it was almost a FAQ. My bad.

**Comment by RaduNico** [comment]
This repository has not received any updates in over 2 years, you can safely assume it will not be updated any time soon. 

As for the hcxtools it is not a renaming as much as it is a complete rewrite of the tool to support the new hashcat format. Wifite would need quite a bit of rework to support the new format.

**Comment by kimocoder** [comment]
This issue is resolved in my fork.

**Comment by Joey0538** [comment]
Gonna check it out now 👍

**Comment by oyeanu** [comment]
check these videos very helpfull for me
https://www.youtube.com/watch?v=qwqaLLY07tI&t=186s

https://www.youtube.com/watch?v=U9v6T4zDbTs

**Comment by Joey0538** [comment]
Fork Kimocoder's wifite2. Pretty simple fix! :)
Attaching the link for fix: https://github.com/kimocoder/wifite2
