### ISSUE TITLE
Value Error abend

### ISSUE THREAD

**Issue by Thurso1761** [derv82/wifite2#30]
the below is the abend on screen message.  Crashed at random times, but always the same error message (less the MAC address).

[!] Error: invalid literal for int() with base 10: 'B0:7F:B9:1A:AC:38'
 [!] Full stack trace below
 [!]    Traceback (most recent call last):
 [!]    File "./Wifite.py", line 200, in <module>
 [!]        w.main()
 [!]    File "./Wifite.py", line 38, in main
 [!]        self.run()
 [!]    File "./Wifite.py", line 82, in run
 [!]        s = Scanner()
 [!]    File "/root/wifite2/py/Scanner.py", line 40, in __init__
 [!]        self.targets = airodump.get_targets()
 [!]    File "/root/wifite2/py/Airodump.py", line 141, in get_targets
 [!]        targets = Airodump.get_targets_from_csv(csv_filename)
 [!]    File "/root/wifite2/py/Airodump.py", line 197, in get_targets_from_csv
 [!]        client = Client(row)
 [!]    File "/root/wifite2/py/Client.py", line 26, in __init__
 [!]        self.packets = int(fields[4].strip())
 [!]    ValueError: invalid literal for int() with base 10: 'B0:7F:B9:1A:AC:38'

**Comment by derv82** [comment]
I also had issues parsing the Clients from the `airodump-ng` output. Seems to have appeared since adding the `--write-interval 1` option (to update every second instead of every 5 seconds).

I thought this was fixed in [this commit](https://github.com/derv82/wifite2/commit/c812edf630e14572551db689bf10c773ad10d6b6#diff-60887ae398c2e0795ba5bbc77cafc040)

Can you confirm that you have the commit above (`except IndexError, ValueError:`) *and* are still seeing this issue?

**Comment by Thurso1761** [comment]
Derv -- I do have the Index, ValueError at Line 198.
Could the problem be -- In py/Client.py, line 26 "int(fields[4].strip())" change int to str???

**Comment by Thurso1761** [comment]
Opps..wrong button.

**Comment by jhoutromundo** [comment]
I got the same error on running with Raspberry Pi 3 + wireless interface. 

 [!] Error: invalid literal for int() with base 10: 'D8'

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "./Wifite.py", line 201, in <module>
 [!]        w.main()
 [!]    File "./Wifite.py", line 39, in main
 [!]        self.run()
 [!]    File "./Wifite.py", line 83, in run
 [!]        s = Scanner()
 [!]    File "/root/wifite2/py/Scanner.py", line 40, in __init__
 [!]        self.targets = airodump.get_targets()
 [!]    File "/root/wifite2/py/Airodump.py", line 141, in get_targets
 [!]        targets = Airodump.get_targets_from_csv(csv_filename)
 [!]    File "/root/wifite2/py/Airodump.py", line 197, in get_targets_from_csv
 [!]        client = Client(row)
 [!]    File "/root/wifite2/py/Client.py", line 26, in __init__
 [!]        self.packets = int(fields[4].strip())
 [!]    ValueError: invalid literal for int() with base 10: 'D8'

**Comment by MisterBianco** [comment]
It appears to be treating the fields value as an int object. 
A Mac address isn't an int. 

May need a regex expression to check that a value is valid?

**Comment by derv82** [comment]
Bug was my bad python. Fixed in https://github.com/derv82/wifite2/commit/af5e3aaca960e2df2629522d11677b39be3305ad

```
try:
    ...
except IndexError, ValueError:
    # Only catches IndexError.
    # ValueError is a *variable* holding the IndexError !
```
