### ISSUE TITLE
Wifite cannot find  any interfaces in monitor mode! Help greatly appreciated

### ISSUE THREAD

**Issue by ice-thanatos** [derv82/wifite2#358]
![Wifite](https://user-images.githubusercontent.com/92143732/136514304-6949605e-3917-4025-a530-fa73b4d30708.PNG)

**Comment by nadesh00** [comment]
start deploying wifite with wifi-card in managed mode, then try deploying again. If it still exists Prolly there's some problem with your wifi card.
