### ISSUE TITLE
new feature: adding option to use bully

### ISSUE THREAD

**Issue by kimocoder** [derv82/wifite2#39]
* Adding option to use "bully" instead of "reaver"

**Comment by derv82** [comment]
Lots of things don't work with Bully right now (CLI options for rate-limiting, auto-timeout, stop after X failures).

And I'm pretty sure Wifite was using Bully for a while; something I was experimenting before my hiatus. Wifite now uses `reaver` by default, but can be changed via the `--bully` option.

**Comment by kimocoder** [comment]
Yes this report is kinda old, should have closed it earlier. The way it works now is the best solution. Thanks
