### ISSUE TITLE
--Dict not set

### ISSUE THREAD

**Issue by Robiii97** [derv82/wifite2#41]
When i captured the handshake wifite says not cracking because --dict not set.. how do i solve this? when i run wifite.py --dict   it says it is not a command.

Iam running one plus one kali nethunter wifite2

**Comment by ritiek** [comment]
You need to run `wifite.py --dict <dict.txt>` where `<dict.txt>` is path to the wordlist that will be used for cracking the password.

The wordlist should look something like below:

```
password
password123
12345678
....
```
You can find wordlists on the internet easily.

The password will be cracked only if it is contained in the wordlist.

**Comment by Robiii97** [comment]
Thanks for your reply!

I have another problem. Wifite doesn't see WPS enabled network's it says all networks in my area don't have WPS but i know that some of them have WPS enabled.

**Comment by ritiek** [comment]
Not sure about that but there has been some discussion on it in #8.

**Comment by Robiii97** [comment]
I already fixed it.
i update reaver to version 1.6.1  (was 1.5.2)
and i updated pixiewps to 1.2

**Comment by kimocoder** [comment]
Great you guys found it. Reaver is gjetting looots og update these days :)

**Comment by derv82** [comment]
Looks resolved. Reopen if there's still problems.

**Comment by vikram4l0** [comment]
how to wifite worldlist top4800 change to rockyou.txt
