### ISSUE TITLE
why my airodump doesn't support --write-interval option?

### ISSUE THREAD

**Issue by daggerly** [derv82/wifite2#42]
my host is ubuntu 16.04 and airodump-ng version is 1.2 beta3
it doesn't support --write-interval option.
Is my airodump-ng too old?

**Comment by MisterBianco** [comment]
Yes its too old you need 1.2 rc4

**Comment by kimocoder** [comment]
Thanks for closing,  airodump-ng questions/issues should be disclosed @ https://github.com.com/aircrack-ng/aircrack-ng which would be the right place, but it's great you got the answers you needed. Have a great weekend

**Comment by MisterBianco** [comment]
That was actually a wifite question and since wifite depends on airodump this was the correct place to ask... 

_Sent from my Samsung SM-N9005 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kimocoder** [comment]
Ah absolutely my mistake sir, did not see the option before checking for it now. From the question I though it was aircrack suite related. 

Sorry, and again have great weekend (whats left of it) (",)
