### ISSUE TITLE
RPI3: WPA client scanning & handshake capturing issue

### ISSUE THREAD

**Issue by kimocoder** [derv82/wifite2#43]
Client(s) scanning & handshake capturing issue(s) on RPI3 run through SSH.
No clients detected when scanning, but on the laptop there is no issues & clients are found again and capturing works again.

Anyone that may try reproducing the problem with an external adapter on RPI3 through SSH connection to ensure this is a problem too? Thanks!

![screenshot_20170712-200109](https://user-images.githubusercontent.com/4252297/28133061-075eea3e-673f-11e7-8caf-af217127fbed.png)

**Comment by ritiek** [comment]
Why did you close this? Sorry, I don't own a Pi 3 but it works fine with my Pi 2.
