### ISSUE TITLE
Airodump exited unexpectedly

### ISSUE THREAD

**Issue by s4w3d0ff** [derv82/wifite2#51]
When running on my rpi3 with command `sudo ./Wifite.py -i wlan1`

```
 [+] Scanning. Found 0 target(s), 0 client(s). Ctrl+C when ready
 [!] Error: Airodump exited unexpectedly! Command ran: airodump-ng wlan1 -a -w /tmp/wifiteuJEH0o/airodump --write-i
terval 1 --output-format pcap,csv

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "./Wifite.py", line 201, in <module>
 [!]        w.main()
 [!]    File "./Wifite.py", line 39, in main
 [!]        self.run()
 [!]    File "./Wifite.py", line 83, in run
 [!]        s = Scanner()
 [!]    File "/home/pi/wifite2/py/Scanner.py", line 38, in __init__
 [!]        % ' '.join(airodump.pid.command))
 [!]  Exception: Airodump exited unexpectedly! Command ran: airodump-ng wlan1 -a -w /tmp/wifiteuJEH0o/airodump --wr
te-interval 1 --output-format pcap,csv
```

When I try the command manualy i get this error:
`airodump-ng: unrecognized option '--write-interval'`

if I remove the --write-interval option it will go through

airodump-ng 1.2

could be related to #30

**Comment by MisterBianco** [comment]
how did you set wlan1 to  monitor mode without renaming it to wlan1mon? did you use a different tool than airmon?

**Comment by s4w3d0ff** [comment]
Ok, so I guess I'm not doing it right... I'm trying to ssh wirelessly to the rpi on wlan0 and run wifite.py on just wlan1. When I run wifite without arguments it disconnects both devices, which closes the ssh session. Is there a way to leave a perticular device alone? This is why I tried '-i wlan1' and fell apon the error.

**Comment by ritiek** [comment]
You need to upgrade your `aircrack-ng` package to `Airodump-ng 1.2 rc4`, the version where the `--write-interval` command gets introduced.

I use 2 WiFi dongles just like you (one for SSH, other for monitoring). It works fine and yes, you need to explicitly use the `-i` option to choose your monitor interface with wifite otherwise you'll lose connection.

**Comment by s4w3d0ff** [comment]
Ok, thank you this worked. 

I upgraded my aircrack-ng package (raspbian apt seems to be on beta, so I built from source) and used `sudo airmon-ng start wlan1` to put the dongle in monitor mode then `sudo ./Wifite.py -i wlan1mon`

It seems to be working fine, thanks again.

**Comment by dozme** [comment]
same on archlinux32, aircrack-ng-1.2rc4-4-i686
but in package aircrack-ng --help wrote aircrack-ng 1.2rc4!

**Comment by jsl303** [comment]
I have AWUS036ACH and Raspberry Pi 3 running on kali-linux-2018.2-rpi3-nexmon.
Airodump-ng is 1.2 rc4, but Wifite indicates that Airodump exited unexpectedly.
It looks like airodump-ng is having a problem creating "/tmp/wifiteGKkMLH/airodump-01.csv".
Here's the log.
 [+] Scanning. Found 33 target(s), 7 client(s). Ctrl+C when ready (decloaked 2 E [+]
Scanning. Found 0 target(s), 0 client(s). Ctrl+C when ready (decloaked 2 ES [!] 
Airodump exited unexpectedly (Code: 0) Command: airodump-ng wlan1 -a -w /tmp/wifiteGKkMLH/airodump --write-interval 1 --output-format pcap,csv

 [!] Error: No targets found. You may need to wait longer, or you may have issues with your wifi card

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/share/wifite/wifite/wifite.py", line 236, in run
 [!]        w.main()
 [!]    File "/usr/share/wifite/wifite/wifite.py", line 47, in main
 [!]        self.run()
 [!]    File "/usr/share/wifite/wifite/wifite.py", line 126, in run
 [!]        targets = s.select_targets()
 [!]    File "/usr/share/wifite/wifite/util/scanner.py", line 183, in select_targets
 [!]        + " or you may have issues with your wifi card")
 [!]  Exception: No targets found. You may need to wait longer, or you may have issues with your wifi card

 [!] Exiting
# airodump-ng wlan1 -a -w /tmp/wifiteGKkMLH/airodump --write-interval 1 --output-format pcap,csv
fopen failed: No such file or directory
Could not create "/tmp/wifiteGKkMLH/airodump-01.csv".
