### ISSUE TITLE
5ghz support

### ISSUE THREAD

**Issue by met0555** [derv82/wifite2#56]
Based on the description on the main page I tried to use the 5ghz option but it doesn't like the parameter

> 5Ghz support for wireless cards that support 5ghz (use -5 option)

```
root@kali:~# wifite  -5
wifite: error: unrecognized arguments: -5
```

WiFite v2 (r87)

thanks

**Comment by vom513** [comment]
This project is for wifite2.  Your description appears to reference the original wifite.

**Comment by met0555** [comment]
you are correct, my bad
