### ISSUE TITLE
WPA Handshake capture fails silently if tshark, pyrit or cowpatty are not available.

### ISSUE THREAD

**Issue by matjohn2** [derv82/wifite2#61]
Noticed when dockerizing a few tools that WiFite2 would show new clients (which I confirmed with wireshark did include a handshake) but wouldn't then move onto the next stage, just sat at "WPA Handhshake capture" with a growing list of clients until the default 500 second timeout.

The issue was any of tshark / pyrit / cowpatty were not available and WiFite2 was calling these periodically to check the capture for WPA hanshakes. 

It may be worth checking for these tools at startup or surfacing an error to the CLI if an exec doesnt happen behind the scenes. 

Probably low priority! :)

**Comment by derv82** [comment]
Checks for required apps (required to attack WPA & most WEP)

https://github.com/derv82/wifite2/blob/1a063edc42e55b4b185715f1719a92feb9b7da78/Wifite.py#L46

And recommended apps (for some WEP & WPS attacks, other optional features like macchanger)

https://github.com/derv82/wifite2/blob/1a063edc42e55b4b185715f1719a92feb9b7da78/Wifite.py#L47
