### ISSUE TITLE
service network-manager start

### ISSUE THREAD

**Issue by reproteq** [derv82/wifite2#70]
Hi derv82 
when open wifite this use network-manager for you normal work but eth0 not show because service is stoped
you can solved this ?
add this
service network-manager start

thanks

**Comment by derv82** [comment]
Looks like there was two problems:

1. Wifite kills network-manager when it runs everytime.
2. Wifite would restart network-manager **only if it put an interface into monitor mode** (during "cleanup").
3. `systemctl start NetworkManager` may not have worked (?)

The fix:

1. Remember if we ever killed `NetworkManager`
2. If we did kill network-manager, restart network-manager when Wifite is stopped.
3. Try to use `service network-manager start` and fall-back to `systemctl` if that fails.
