### ISSUE TITLE
Bug: airodump seems to be leaking out text

### ISSUE THREAD

**Issue by Niller303** [derv82/wifite2#78]
When running wifite2 it seems to be leaking out airodump text
Using the currenty latest commit "Cleaning up handshake code", commit: 5db801b4149eb2694354a1d51754b65224b4c518

```
root@Pineapple:/sd/projects/wifite2# python Wifite.py
  .               .    
.´  ·  .     .  ·  `.  wifite 2.0
:  :  :  (¯)  :  :  :  automated wireless auditor
`.  ·  ` /¯\ ´  ·  .´  https://github.com/derv82/wifite2
  `     /¯¯¯\     ´    

 [!] warning: recommended app cowpatty was not found
 [!] warning: recommended app pyrit was not found
 [!] warning: recommended app stdbuf was not found
 [!] warning: recommended app tshark was not found
 [!] recommended app(s) were not found
 [!] wifite may not work as expected
 [!] if you have problems, try killing these processes (kill -9 PID)

 [+] looking for wireless interfaces

    PHY   Interface   Driver              Chipset                       
-----------------------------------------------------------------------
 1. phy0  wlan0       ath9k               Not pci, usb, or sdio         
 2. phy0  wlan0-1     ath9k               Not pci, usb, or sdio         
 3. phy1  wlan1       rtl8187             Realtek Semiconductor Corp. RTL8187
 4. phy2  wlan2       rt2800usb           Ralink Technology, Corp. RT2870/RT3070

 [+] select interface (1-4): 4
 [+] enabling monitor mode on wlan2... enabled wlan2mon

   NUM                      ESSID   CH  ENCR  POWER  WPS?  CLIENT               
   NUM                      ESSID   CH  ENCR  POWER  WPS?  CLIENT
   NUM                      ESSID   CH  ENCR  POWER  WPS?  CLIENT               
   NUM                      ESSID   CH  ENCR  POWER  WPS?  CLIENT               
   NUM                      ESSID   CH  ENCR  POWER  WPS?  CLIENT               
   NUM                      ESSID   CH  ENCR  POWER  WPS?  CLIENT               
   NUM                      ESSID   CH  ENCR  POWER  WPS?  CLIENT                  NUM                      ESSID   CH  ENCR  POWER  WPS?  CLIENT                                  
---  -------------------------  ---  ----  -----  ----  ------                    
1                     *censored*   11   WPA   70db    no    1                       
2              *censored*    6   WPA   51db    no    1                       
3           *censored*    1   WPA   44db    no                            
4              *censored*   11   WPA   40db    no                        
[+] Scanning. Found 4 target(s), 2 client(s). Ctrl+C when ready (decloaked 1 ESSIDs: *censored*) 
```

**Comment by derv82** [comment]
It's not leaking airodump text... it looks like it's printing the same header over-and-over again.

I made some changes to support Python 3, which includes encoding the airodump output as `utf8`...

Maybe the ESSID of an access point contains non-printable characters?

I'll need:

1. Operating system. Looks like a Pi but more info would help.
2. Python version (`python -V`)
3. Airodump version (`airodump-ng --help | head -3`)
4. The output of `airodump-ng wlan2mon` (after it's in monitor mode):

```
% airmon-ng start wlan2

% airodump-ng -w wifite-issue-78 wlan2mon
# Airodump will write some files to the cwd.
# Let it run for a bit: Wait at least 5 seconds *after* you see the 4 targets that Wifite found above.
# Ctrl+C to stop

% ls
# You should see files starting with "wifite-issue-78".
# Open "wifite-issue-78.csv"
# Censor the BSSIDs (aa:bb:cc:dd:ee:ff) from the CSV for privacy
# Leave ESSIDs if they appear to have any special characters (or just leave them all).
# Upload the wifite-issue-78.csv to this issue.
```

With this info, I can at least re-run Wifite with that CSV and see if I can reproduce the issue.

**Comment by Niller303** [comment]
1. Operating system. Looks like a Pi but more info would help.
Wifi Pineapple MK5, Firmware Version: 2.4.0
Its supposedly OpenWRT based

2. Python version (python -V)
Python 2.7.3

3. Airodump version (airodump-ng --help | head -3)
Airodump-ng 1.2 rc2

4. The output of airodump-ng wlan2mon (after it's in monitor mode):
root@Pineapple:~# airmon-ng start wlan2
Found 3 processes that could cause trouble.
If airodump-ng, aireplay-ng or airtun-ng stops working after
a short period of time, you may want to kill (some of) them!

 2424 root      1628 S    wpa_supplicant -B -P /var/run/wifi-wlan2.pid -D nl80
 2459 root      1536 S    udhcpc -p /var/run/udhcpc-wlan2.pid -s /lib/netifd/d
 5156 root      1520 S    grep wpa_action\|wpa_supplicant\|wpa_cli\|dhclient\|

PHY	Interface	Driver		Chipset

phy0	wlan0		ath9k		Not pci, usb, or sdio
phy0	wlan0-1		ath9k		Not pci, usb, or sdio
phy1	wlan1		rtl8187		Realtek Semiconductor Corp. RTL8187
phy2	wlan2		rt2800usb	Ralink Technology, Corp. RT2870/RT3070
		(mac80211 monitor mode vif enabled for [phy2]wlan2 on [phy2]wlan2mon)
		(mac80211 station mode vif disabled for [phy2]wlan2)

wifite-issue-78-01.csv attatched
[wifite-issue-78-01.csv.txt](https://github.com/derv82/wifite2/files/1866639/wifite-issue-78-01.csv.txt)

**Comment by derv82** [comment]
Can't reproduce when using that CSV:

![image](https://user-images.githubusercontent.com/993464/38176994-12c1d5f6-35ae-11e8-8080-7295c4f52b84.png)

You might be censoring out the ESSID which is triggering the issue. Maybe there's a character that looks ASCII but is actually unicode/emoji or something.

**Comment by Niller303** [comment]
I haven't been able to produce a csv that produced the issue.
I have encountered the issue a couple of times in wifite while trying though.
It seems to happen when an unresolved ESSID gets resolved, but i can't really produce a csv doing that though.

**Comment by derv82** [comment]
Thanks for the info.

I think I can reproduce by running a scan in a shorter-width terminal & decloaking a target:

![image](https://user-images.githubusercontent.com/993464/38445314-df3564b6-39a7-11e8-9ad0-37a7855be798.png)

Sandman suggested I identify "decloaked" ESSIDs using a `*` character at the end of the ESSID name, instead of printing the `decloaked X essids: ...` which could become very long very quickly.

Let me see what I can do.

**Comment by derv82** [comment]
Ok, latest version shouldn't print out as much. Give it a try and see if the output looks better.

FYI, decloaked ESSIDs will look like this (with a purple `*` to the right of the ESSID):

![image](https://user-images.githubusercontent.com/993464/38447623-551d92ce-39b3-11e8-8de4-82c683629ef5.png)

**Comment by Niller303** [comment]
Ya its fixed
