### ISSUE TITLE
Not working on Nethunter 

### ISSUE THREAD

**Issue by hxrofo** [derv82/wifite2#83]
hi guys !
any one facing this issue with wifite on kali nethunter? (see the screenshots)
I have a nexus 5, and I can put wlan0 in monitor mode with the command **source monstart-nh** and it works fine with the older version of wifite
any help would be appreciated
thanks
![2](https://user-images.githubusercontent.com/17935737/39675266-8e5b431a-5150-11e8-888b-e32f7b7fbb96.png)
![1](https://user-images.githubusercontent.com/17935737/39675267-8f333b44-5150-11e8-8041-3ff967705d44.png)

**Comment by kimocoder** [comment]
wifite2 was just pushed to Kali, so I bet not many people have tested it yet.
I see they've pushed the release version (v2.1.0 BETA) to repos. Developer has to take a look at it.

**Comment by derv82** [comment]
I'll need some info (screenshots) of the output of some commands in order to help troubleshoot the issue further.

What happens when you run:

1. `airmon-ng`
2. `iwconfig wlan0`
3. `ifconfig wlan0`
4. `airodump-ng --help | head -5`
5. `airodump-ng wlan0`

**Comment by hxrofo** [comment]
here are 4 screenshots. The last command "airodump-ng wlan0" works fine and gives me a list of APs and connected clients.
![31958285_10216421956724433_7684657908088307712_n](https://user-images.githubusercontent.com/17935737/39675595-39b84858-5155-11e8-879d-26aa0ed76c3a.png)
![31949586_10216421958044466_5481415182175436800_n](https://user-images.githubusercontent.com/17935737/39675596-39fd5a7e-5155-11e8-9af7-05b46ce3b514.png)
![31543919_10216421957844461_7244743134016438272_n](https://user-images.githubusercontent.com/17935737/39675597-3a3d3d38-5155-11e8-9aa9-caabe4c3091c.png)
![31531048_10216421957044441_5901616494445330432_n](https://user-images.githubusercontent.com/17935737/39675598-3a9e8e44-5155-11e8-9dc0-c6c6d91e7202.png)

**Comment by ifarazshareef1997fz-rgb** [comment]
Hack WhatsApp

**Comment by ifarazshareef1997fz-rgb** [comment]
Hack
