### ISSUE TITLE
not an issue but a clarification about ASTERISK on essid

### ISSUE THREAD

**Issue by Mr-P3rry** [derv82/wifite2#87]
hi, I was wondering why in some essid I can find an asterisk? Does it mean something?  I couldn't find anything regarding this. Thanks 

![whatsapp image 2018-05-25 at 12 07 39](https://user-images.githubusercontent.com/16190074/40539351-c7a0819e-6014-11e8-9ade-63d3e2b0f9d3.jpeg)

**Comment by derv82** [comment]
Explained in #78 

> FYI, decloaked ESSIDs will look like this (with a purple * to the right of the ESSID)

I'll try to add this note to the Wifite output or in the README somewhere.

**Comment by yarodevuci** [comment]
@derv82 meaning SSID of that wifi was hidden?

**Comment by Mr-P3rry** [comment]
yes. I got it.

**Comment by PapiChulo-M2i** [comment]
I can confirm that these are the masked ESSIDs.  I've been able to test it.
