### ISSUE TITLE
Error: No module named hostapd

### ISSUE THREAD

**Issue by aeroroland** [derv82/wifite2#89]
Fresh clone on ubuntu 18.04, when running Wifite.py, get the following error:

`  .               .    
.´  ·  .     .  ·  `.  wifite 2.1.5
:  :  :  (¯)  :  :  :  automated wireless auditor
`.  ·  ` /¯\ ´  ·  .´  https://github.com/derv82/wifite2
  `     /¯¯¯\     ´    

 [!] Error: No module named hostapd

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/git/wifite2/wifite/wifite.py", line 264, in run
 [!]        w.main()
 [!]    File "/git/wifite2/wifite/wifite.py", line 36, in main
 [!]        self.dependency_check()
 [!]    File "/git/wifite2/wifite/wifite.py", line 58, in dependency_check
 [!]        from .tools.hostapd import Hostapd
 [!]    ImportError: No module named hostapd

 [!] Exiting`

When I look in the tools directory, I don't see an obvious hostapd. I have it installed independently through the package manager, as well.

**Comment by derv82** [comment]
My bad. I'm working on EvilTwin stuff on a separate branch; hostapd should not be required.
