### ISSUE TITLE
Any chance of adding back WPS PIN attack? 

### ISSUE THREAD

**Issue by seanbperiod** [derv82/wifite2#90]
I know it's not efficient, but many routers aren't compatible with pixiedust. Perhaps adding it as a switch option?

**Comment by ravenphreaker** [comment]
The reason it was taken out and derv82 please correct me if i am wrong is the pin attack is no longer viable as any router that has been updated is protected by usually shutting down wps querie after 3 attempts. Then you are timed out for anywhere between 5 to 30 minutes then you only get three more attempts and them have to wait again. or they outright ban your mac.

**Comment by kimocoder** [comment]
It took too long time to complete. WPS lockout may be avoided with mdk4, therefor I support that the WPS pin attack should come back (as optional maybe) but also, mdk4 support should be added (see my other issue report on the matter)

**Comment by derv82** [comment]
I'll add WPS PIN attack back in if it's viable in a significant amount of routers.

From my personal testing, I've only been able to use the WPS-PIN attack on a single router I owned, and it took about 2 days. With my laptop inches from the router.

From what I understand, MDK4 can overwhelm a router to where it stops working. At which point someone will manually reboot the router. If that's the case, then I don't think it's viable in Wifite... Correct me if I'm wrong.

If there's a popular model of router that is susceptible, or if MDK4 can reset the lockout instantly, then I'll look at adding it back in. But it was a pain to maintain and manage the various ways `bully` and `reaver` output the status of the WPS PIN attack, detecting lockouts, retrying the same PIN over and over, etc.

**Comment by rafaleon69** [comment]
Hey derv82 I have confirmed NULL attack PIN vector on at least two routers. You can read more on that on my blog. But long story short Null Pin works on  BT Home Hub 3.0B running BCM6361 and EE-Smart-Hub running on Atheros chipset.
more on: https://hackabean.blogspot.com/

**Comment by osysltd** [comment]
Yep, origin implementation is very helpful in major times

**Comment by RChadwick7** [comment]
+1 for adding WPS
Personally, I've never seen Pixie work, but have had better results with WPS PIN.

**Comment by derv82** [comment]
The masses have spoken. I'll add this back when I get a chance; although it's quite a lot of work, and I'd rather finish the EvilTwin implementation I started... So this will be *Low Priority*.

**Comment by derv82** [comment]
Ok, `2.2.3` has brought back WPS PIN attack.

I tested with both `reaver` and `bully` and it seems to work for me on my test router (thanks again to @kimocoder for the router!).

Release notes has more info: https://github.com/derv82/wifite2/releases/tag/2.2.3

If you guys find any bugs with the PIN attack (or any bugs anywhere!) just create an issue and I'll look into it.

**Comment by seanbperiod** [comment]
low priority then released 5 days later. you are killing it. Thanks!

**Comment by RChadwick7** [comment]
While I'm glad it's back, is there a way to disable it?

**Comment by kimocoder** [comment]
@seanbperiod this feature has been added again, this issue report may be closed :1st_place_medal:  thanks!

**Comment by seanbperiod** [comment]
Excellent work. Thanks!
