### ISSUE TITLE
invalid sheband string

### ISSUE THREAD

**Issue by blshkv** [derv82/wifite2#99]
https://github.com/derv82/wifite2/blob/master/wifite/wifite.py#L1
ment to be 2.7 I guess,

but the best would be to have  ```#!/usr/bin/env python ``` everywhere since both python2 and python3 are supported.

**Comment by derv82** [comment]
Whoops. Changed them all to `#!/usr/bin/env python` since I guess we're supporting Python3 now 😏 

Thanks!
